### ISSUE TITLE
Can not get orientation exif infomation of image captured with camera plugin

### ISSUE THREAD

**Issue by ltvu93** [bigflood/dartexif#8] opened 2019-06-20 04:50 UTC
When I use your example in https://github.com/bigflood/exifviewer, I cannot get orientation info of the captured image with camera plugin, but the picked image have this info. This is a bug in your library or camera plugin do not write orientation info to the captured image?

![Screenshot_20190620-110930](https://user-images.githubusercontent.com/12897718/59818054-8209f900-934c-11e9-862c-71553296fff1.png)
![Screenshot_20190620-110953](https://user-images.githubusercontent.com/12897718/59818108-ab2a8980-934c-11e9-8055-525b8a53e2ce.png)

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.7.5-pre.21, on Microsoft Windows [Version 10.0.17763.557], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
[√] Android Studio (version 3.4)
[√] VS Code (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by bigflood** [comment] 2019-06-20 08:29
Duplicate of #6

**Closed by bigflood** 2019-06-20 08:29 UTC
